### ISSUE TITLE
Add context.entity.location.simple to mm denizen death

### ISSUE THREAD

**Issue by SXRWahrheit** [BerndiVader/mmDenizenAddon#3] opened 2017-06-05 00:29 UTC
Please and thank you! I need this for anti-farm scripts.

**Comment by BerndiVader** [comment] 2017-06-05 10:17
@SXRWahrheit I added **<context.entity>** to the death event. Though it was already possible by using **<context.activemob.location>**. On this occasion added <activemob.entity> to dActiveMob object because it did not exist.

**Comment by SXRWahrheit** [comment] 2017-06-05 13:20
Would I do it like this?

```
        on mm denizen death:
        - flag server spawnlimit.<context.location>:++ duration:30m
        - if <server.flag[spawnlimit.<context.location>]> >= 3 {
            - determine drops:li@
            - determine money:0
            - determine exp:0
        }
```

Just FYI, regular Denizen code for the same function (for non mythicmobs) looks like this:

```
"No Farms For You":
    type: world
    events:
        on entity dies:
        - flag server spawnlimit.<context.entity.location.simple>:++ duration:30m
        - if <server.flag[spawnlimit.<context.entity.location.simple>]> >= 3 {
            - determine NO_DROPS_OR_XP
        }   
```

**Comment by BerndiVader** [comment] 2017-06-05 15:25
Oh sorry i made a mistake, its called <context.victim> to get the dEntity of the mythicmob mob.

Anyway, you get the dObjects as usual in denizen: _<context.activemob.location>_ to get a dLocation _<context.victim>_ or _<context.activemob.entity>_ to get the dEntity. Because they are dObjects you can use them just like all other denizen objects: If you use _<context.entity.location.simple>_ in denizen death event you can use _<context.victim.location.simple>_ or _<context.activemob.location.simple>_ in mm death event.

```
        on mm denizen death:
        - flag server spawnlimit.<context.activemob.location.simple>:++ duration:30m
        - if <server.flag[spawnlimit.<context.activemob.location.simple>]> >= 3 {
            - determine drops:li@
            - determine money:0
            - determine exp:0
        }
```

**Comment by SXRWahrheit** [comment] 2017-06-05 15:46
This appears to prevent drops but not money or exp:

```
"No Farms For You":
    type: world
    events:
        on entity dies:
        - flag server spawnlimit.<context.entity.location.simple>:++ duration:30m
        - if <server.flag[spawnlimit.<context.entity.location.simple>]> >= 3 {
            - determine NO_DROPS_OR_XP
        }        
        on mm denizen death:
        - flag server spawnlimit.<context.activemob.location.simple>:++ duration:30m
        - if <server.flag[spawnlimit.<context.activemob.location.simple>]> >= 3 {
            - determine drops:li@
            - determine money:0
            - determine exp:0
        }
```

```
[16:46:08] [Server thread/INFO]: +> Executing 'FLAG': 
                   flag_name='SPAWNLIMIT.-7383,22,-5912,PROSPERUS'  
                   Action/Value='INCREASE(1)'  duration='d@1800.0s'  
                   flag_target='server' 
[16:46:08] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_ChainFrontpageTears' Executing: 
                   IF 
                   "<server.flag[spawnlimit.<context.activemob.location.simple>]>" 
                   ">=" "3" "{" "-" "determine" "drops:li@" "-" "determine" 
                   "money:0" "-" "determine" "exp:0" "}" 
[16:46:08] [Server thread/INFO]: +- Executing dCommand: IF ---------+ 
[16:46:08] [Server thread/INFO]: +> Executing 'IF': use_braces='true' 
[16:46:08] [pool-801-thread-1/INFO]:  Filled tag <context.activemob.location.simple> with 
                   '-7383,22,-5912,prosperus'. 
[16:46:08] [Server thread/INFO]:  Filled tag 
                   <server.flag[spawnlimit.-7383,22,-5912,prosperus]> with 
                   '66.0'. 
[16:46:08] [Server thread/INFO]:  Comparable='Decimal(66.0)', Operator='OR_MORE', 
                   ComparedTo='Decimal(3.0)' --> OUTCOME='true' 
[16:46:08] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_ChainFrontpageTears' Executing: 
                   DETERMINE "drops:li@" 
[16:46:08] [Server thread/INFO]: +- Executing dCommand: DETERMINE ---------+ 
[16:46:08] [Server thread/INFO]: +> Executing 'DETERMINE': outcome='drops:li@'  
                   passively='false' 
[16:46:08] [Server thread/INFO]:  Completing queue 'NO FARMS FOR YOU_ChainFrontpageTears' 
                   in 1ms. 
[16:46:08] [Server thread/INFO]:  Running script event 'EntityDies', event='entity dies' 
                   for script 'NO FARMS FOR YOU' 
[16:46:08] [Server thread/INFO]:  Starting InstantQueue 'NO FARMS FOR 
                   YOU_PollCraftAlignment'... 
[16:46:08] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_PollCraftAlignment' Executing: 
                   FLAG "server" 
                   "spawnlimit.<context.entity.location.simple>:++" 
                   "duration:30m" 
[16:46:08] [Server thread/INFO]: +- Executing dCommand: FLAG ---------+ 
[16:46:08] [Server thread/INFO]:  Filled tag <context.entity.location.simple> with 
                   '-7383,22,-5912,prosperus'. 
[16:46:08] [Server thread/INFO]: +> Executing 'FLAG': 
                   flag_name='SPAWNLIMIT.-7383,22,-5912,PROSPERUS'  
                   Action/Value='INCREASE(1)'  duration='d@1800.0s'  
                   flag_target='server' 
[16:46:08] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_PollCraftAlignment' Executing: IF 
                   "<server.flag[spawnlimit.<context.entity.location.simple>]>" 
                   ">=" "3" "{" "-" "determine" "NO_DROPS_OR_XP" "}" 
[16:46:08] [Server thread/INFO]: +- Executing dCommand: IF ---------+ 
[16:46:08] [Server thread/INFO]: +> Executing 'IF': use_braces='true' 
[16:46:08] [pool-804-thread-1/INFO]:  Filled tag <context.entity.location.simple> with 
                   '-7383,22,-5912,prosperus'. 
[16:46:08] [Server thread/INFO]:  Filled tag 
                   <server.flag[spawnlimit.-7383,22,-5912,prosperus]> with 
                   '67.0'. 
[16:46:08] [Server thread/INFO]:  Comparable='Decimal(67.0)', Operator='OR_MORE', 
                   ComparedTo='Decimal(3.0)' --> OUTCOME='true' 
[16:46:08] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_PollCraftAlignment' Executing: 
                   DETERMINE "NO_DROPS_OR_XP" 
[16:46:08] [Server thread/INFO]: +- Executing dCommand: DETERMINE ---------+ 
[16:46:08] [Server thread/INFO]: +> Executing 'DETERMINE': outcome='NO_DROPS_OR_XP'  
                   passively='false' 
[16:46:08] [Server thread/INFO]:  Completing queue 'NO FARMS FOR YOU_PollCraftAlignment' in 
                   1ms. 
[16:46:08] [Server thread/INFO]:  Running script event 'MythicMobsDeathEvent', event='mm 
                   denizen death' for script 'NO FARMS FOR YOU' 
[16:46:08] [Server thread/INFO]:  Starting InstantQueue 'NO FARMS FOR 
                   YOU_RegulationsInsulationLouis'... 
[16:46:08] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_RegulationsInsulationLouis' 
                   Executing: FLAG "server" 
                   "spawnlimit.<context.activemob.location.simple>:++" 
                   "duration:30m" 
[16:46:08] [Server thread/INFO]: +- Executing dCommand: FLAG ---------+ 
[16:46:08] [Server thread/INFO]:  Filled tag <context.activemob.location.simple> with 
                   '-7383,22,-5912,prosperus'. 
[16:46:08] [Server thread/INFO]: +> Executing 'FLAG': 
                   flag_name='SPAWNLIMIT.-7383,22,-5912,PROSPERUS'  
                   Action/Value='INCREASE(1)'  duration='d@1800.0s'  
                   flag_target='server' 
[16:46:08] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_RegulationsInsulationLouis' 
                   Executing: IF 
                   "<server.flag[spawnlimit.<context.activemob.location.simple>]>" 
                   ">=" "3" "{" "-" "determine" "drops:li@" "-" "determine" 
                   "money:0" "-" "determine" "exp:0" "}" 
[16:46:08] [Server thread/INFO]: +- Executing dCommand: IF ---------+ 
[16:46:08] [Server thread/INFO]: +> Executing 'IF': use_braces='true' 
[16:46:08] [pool-807-thread-1/INFO]:  Filled tag <context.activemob.location.simple> with 
                   '-7383,22,-5912,prosperus'. 
[16:46:08] [Server thread/INFO]:  Filled tag 
                   <server.flag[spawnlimit.-7383,22,-5912,prosperus]> with 
                   '68.0'. 
[16:46:08] [Server thread/INFO]:  Comparable='Decimal(68.0)', Operator='OR_MORE', 
                   ComparedTo='Decimal(3.0)' --> OUTCOME='true' 
[16:46:08] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_RegulationsInsulationLouis' 
                   Executing: DETERMINE "drops:li@" 
[16:46:08] [Server thread/INFO]: +- Executing dCommand: DETERMINE ---------+ 
[16:46:08] [Server thread/INFO]: +> Executing 'DETERMINE': outcome='drops:li@'  
                   passively='false' 
[16:46:08] [Server thread/INFO]:  Completing queue 'NO FARMS FOR 
                   YOU_RegulationsInsulationLouis' in 1ms. 
```

**Comment by SXRWahrheit** [comment] 2017-06-05 15:53
Also do you support context.reason? For example:

```
"No Spawners For You":
    type: world
    events:
        on entity spawns:
        - if '<context.reason>' == 'SPAWNER'
        {
          - flag '<context.entity>' 'is_spawned.spawner'
        }
        on entity dies:
        - if '<context.entity.flag[is_spawned.spawner]>'
        {
          - determine NO_DROPS_OR_XP
        }
        on mm denizen spawn:
        - if '<context.reason>' == 'SPAWNER'
        {
          -flag '<context.activemob>' 'is_spawned.spawner'
        }
        on mm denizen death:
        - if '<context.activemob.flag[is_spawned.spawner]>'
            - determine drops:li@
            - determine money:0
            - determine exp:0
        }
```

**Comment by BerndiVader** [comment] 2017-06-05 16:55
You flag the entity in the _entity spawn even_t and in the _entity dies event_ you check for _entity.flag_ and so you should do in the _mm death event_: _<context.activemob.entity.flag[is_spawned.spawner]>_ You can drop the mm spawn event. Btw, there is a way you can check if the entity is a mythicmobs mob and get the dActiveMob from it. This work for the spawn event too, but you have to wait a tick, this is the time mythicmobs needs to register the activemob. With the use of this you can go a step further and add a mythicspawner flag to the entity if the entity is a mythicmobs mob that was spawned by a mythicspawner:

```
	on entity spawns:
	  - wait 0.2s
	  - if <context.entity.isactivemob> && <context.entity.activemob.hasmythicspawner> {
		- flag <context.entity.is_spawned.mythicspawner>
	  }
```

**Comment by SXRWahrheit** [comment] 2017-06-05 17:03
I will try that, thanks. But what about the issue with the determine commands not working? It looks like the script stops after determine drops.

**Comment by BerndiVader** [comment] 2017-06-05 19:17
I look into it.

**Comment by SXRWahrheit** [comment] 2017-06-05 19:18
Thanks! I'm using this in the VanillaDrops MM file:

```
BlazeDrops:
  Drops:
  - exp 30 1
  - money 5 1
  - blaze_rod 0-3 1
  - glowstone_dust 0-6 1
CaveSpiderDrops:
  Drops:
  - exp 15 1
  - money 3
  - string 0-6 1
  - spider_eye 0-3 1
CreeperDrops:
  Drops:
  - exp 15 1
  - money 3 1
  - sulphur 0-6 1
EndermanDrops:
  Drops:
  - exp 15 1
  - money 3 1
  - ender_pearl 0-3 1
GuardianDrops:
  Drops:
  - exp 30 1
  - money 5 1
  - prismarine_shard 0-6 1
  - raw_fish 0-3 0.4
  - prismarine_crystal 0-3 0.4
HuskDrops:
  Drops:
  - exp 15 1
  - money 3 1
  - rotten_flesh 0-6 1
SkeletonDrops:
  Drops:
  - exp 15 1
  - money 3 1
  - arrow 0-6 1
  - bone 0-6 1
SlimeDrops:
  Drops:
  - exp 12 1
  - money 1 1
  - slime_ball 0-4 1
SpiderDrops:
  Drops:
  - exp 15 1
  - money 3 1
  - string 0-6 1
  - spider_eye 0-3 1
WitchDrops:
  Drops:
  - exp 15 1
  - money 3 1
  - glass_bottle 0-6 0.125
  - glowstone_dust 0-6 0.125
  - sulphur 0-6 0.125
  - redstone 0-6 0.125
  - spider_eye 0-6 0.125
  - sugar 0-6 0.125
  - stick 0-6 0.25
ZombieDrops:
  Drops:
  - exp 15 1
  - money 3 1
  - rotten_flesh 0-6 1

**Comment by BerndiVader** [comment] 2017-06-06 08:47
Issue is fixed by using a list separeted with ";" Reason for this is the fact that determine can only be called once (ofcourse) and it should be always at the end of the code, because it also cancel the rest of the script. As you already noticed. Thats a denizen thing btw so in all events if you use determine it will stop the script after this command is called.

**Comment by SXRWahrheit** [comment] 2017-06-06 12:25
So like this?
```
            - determine drops:li@;money:0;exp:0
```

**Comment by BerndiVader** [comment] 2017-06-06 14:36
Yes. Thats how to use it.

**Comment by SXRWahrheit** [comment] 2017-06-06 19:06
It looks like it's still not working; mobs still drop exp, items, and gold.

```

"No Farms For You":
    type: world
    events:
        on entity dies:
        - flag server spawnlimit.<context.entity.location.simple>:++ duration:30m
        - if <server.flag[spawnlimit.<context.entity.location.simple>]> >= 3 
        {
            - determine NO_DROPS_OR_XP
            - narrate "Debug message"
        }
        on mm denizen death:
        - flag server spawnlimit.<context.activemob.location.simple>:++ duration:30m
        - if <server.flag[spawnlimit.<context.activemob.location.simple>]> >= 3 
        {
            - determine drops:li@;money:0;exp:0
            - narrate "Debug message"
        }

```

```

[20:04:14] [Server thread/INFO]:  Running script event 'EntityDies', event='entity dies' 
                   for script 'NO FARMS FOR YOU' 
[20:04:14] [Server thread/INFO]:  Starting InstantQueue 'NO FARMS FOR 
                   YOU_OkayJunctionBiodiversity'... 
[20:04:14] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_OkayJunctionBiodiversity' 
                   Executing: FLAG "server" 
                   "spawnlimit.<context.entity.location.simple>:++" 
                   "duration:30m" 
[20:04:14] [Server thread/INFO]: +- Executing dCommand: FLAG ---------+ 
[20:04:14] [Server thread/INFO]:  Filled tag <context.entity.location.simple> with 
                   '-7383,22,-5912,prosperus'. 
[20:04:14] [Server thread/INFO]: +> Executing 'FLAG': 
                   flag_name='SPAWNLIMIT.-7383,22,-5912,PROSPERUS'  
                   Action/Value='INCREASE(1)'  duration='d@1800.0s'  
                   flag_target='server' 
[20:04:14] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_OkayJunctionBiodiversity' 
                   Executing: IF 
                   "<server.flag[spawnlimit.<context.entity.location.simple>]>" 
                   ">=" "3" "{" "-" "determine" "NO_DROPS_OR_XP" "-" 
                   "narrate" "Debug message" "}" 
[20:04:14] [Server thread/INFO]: +- Executing dCommand: IF ---------+ 
[20:04:14] [Server thread/INFO]: +> Executing 'IF': use_braces='true' 
[20:04:14] [pool-1486071-thread-1/INFO]:  Filled tag <context.entity.location.simple> with 
                   '-7383,22,-5912,prosperus'. 
[20:04:14] [Server thread/INFO]:  Filled tag 
                   <server.flag[spawnlimit.-7383,22,-5912,prosperus]> with 
                   '17.0'. 
[20:04:14] [Server thread/INFO]:  Comparable='Decimal(17.0)', Operator='OR_MORE', 
                   ComparedTo='Decimal(3.0)' --> OUTCOME='true' 
[20:04:14] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_OkayJunctionBiodiversity' 
                   Executing: DETERMINE "NO_DROPS_OR_XP" 
[20:04:14] [Server thread/INFO]: +- Executing dCommand: DETERMINE ---------+ 
[20:04:14] [Server thread/INFO]: +> Executing 'DETERMINE': outcome='NO_DROPS_OR_XP'  
                   passively='false' 
[20:04:14] [Server thread/INFO]:  Completing queue 'NO FARMS FOR 
                   YOU_OkayJunctionBiodiversity' in 64ms. 
[20:04:14] [Server thread/INFO]:  Running script event 'MythicMobsDeathEvent', event='mm 
                   denizen death' for script 'NO FARMS FOR YOU' 
[20:04:14] [Server thread/INFO]:  Starting InstantQueue 'NO FARMS FOR 
                   YOU_RedeemSurfSpots'... 
[20:04:14] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_RedeemSurfSpots' Executing: FLAG 
                   "server" 
                   "spawnlimit.<context.activemob.location.simple>:++" 
                   "duration:30m" 
[20:04:14] [Server thread/INFO]: +- Executing dCommand: FLAG ---------+ 
[20:04:14] [Server thread/INFO]:  Filled tag <context.activemob.location.simple> with 
                   '-7383,22,-5912,prosperus'. 
[20:04:14] [Server thread/INFO]: +> Executing 'FLAG': 
                   flag_name='SPAWNLIMIT.-7383,22,-5912,PROSPERUS'  
                   Action/Value='INCREASE(1)'  duration='d@1800.0s'  
                   flag_target='server' 
[20:04:14] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_RedeemSurfSpots' Executing: IF 
                   "<server.flag[spawnlimit.<context.activemob.location.simple>]>" 
                   ">=" "3" "{" "-" "determine" "drops:li@;money:0;exp:0" "-" 
                   "narrate" "Debug message" "}" 
[20:04:14] [Server thread/INFO]: +- Executing dCommand: IF ---------+ 
[20:04:14] [Server thread/INFO]: +> Executing 'IF': use_braces='true' 
[20:04:14] [pool-1486074-thread-1/INFO]:  Filled tag <context.activemob.location.simple> with 
                   '-7383,22,-5912,prosperus'. 
[20:04:14] [Server thread/INFO]:  Filled tag 
                   <server.flag[spawnlimit.-7383,22,-5912,prosperus]> with 
                   '18.0'. 
[20:04:14] [Server thread/INFO]:  Comparable='Decimal(18.0)', Operator='OR_MORE', 
                   ComparedTo='Decimal(3.0)' --> OUTCOME='true' 
[20:04:14] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_RedeemSurfSpots' Executing: 
                   DETERMINE "drops:li@;money:0;exp:0" 
[20:04:14] [Server thread/INFO]: +- Executing dCommand: DETERMINE ---------+ 
[20:04:14] [Server thread/INFO]: +> Executing 'DETERMINE': 
                   outcome='drops:li@;money:0;exp:0'  passively='false' 
[20:04:14] [Server thread/INFO]:  Completing queue 'NO FARMS FOR YOU_RedeemSurfSpots' in 
                   21ms. 
[20:04:42] [Server thread/INFO]:  Running script event 'EntityDies', event='entity dies' 
                   for script 'NO FARMS FOR YOU' 
[20:04:42] [Server thread/INFO]:  Starting InstantQueue 'NO FARMS FOR 
                   YOU_FortuneScubaHh'... 
[20:04:42] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_FortuneScubaHh' Executing: FLAG 
                   "server" "spawnlimit.<context.entity.location.simple>:++" 
                   "duration:30m" 
[20:04:42] [Server thread/INFO]: +- Executing dCommand: FLAG ---------+ 
[20:04:42] [Server thread/INFO]:  Filled tag <context.entity.location.simple> with 
                   '-1658,10,2437,prosperus'. 
[20:04:42] [Server thread/INFO]: +> Executing 'FLAG': 
                   flag_name='SPAWNLIMIT.-1658,10,2437,PROSPERUS'  
                   Action/Value='INCREASE(1)'  duration='d@1800.0s'  
                   flag_target='server' 
[20:04:42] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_FortuneScubaHh' Executing: IF 
                   "<server.flag[spawnlimit.<context.entity.location.simple>]>" 
                   ">=" "3" "{" "-" "determine" "NO_DROPS_OR_XP" "-" 
                   "narrate" "Debug message" "}" 
[20:04:42] [Server thread/INFO]: +- Executing dCommand: IF ---------+ 
[20:04:42] [Server thread/INFO]: +> Executing 'IF': use_braces='true' 
[20:04:42] [pool-1486077-thread-1/INFO]:  Filled tag <context.entity.location.simple> with 
                   '-1658,10,2437,prosperus'. 
[20:04:42] [Server thread/INFO]:  Filled tag 
                   <server.flag[spawnlimit.-1658,10,2437,prosperus]> with 
                   '1.0'. 
[20:04:42] [Server thread/INFO]:  Comparable='Decimal(1.0)', Operator='OR_MORE', 
                   ComparedTo='Decimal(3.0)' --> OUTCOME='false' 
[20:04:42] [Server thread/INFO]:  Completing queue 'NO FARMS FOR YOU_FortuneScubaHh' in 
                   1ms. 
[20:04:51] [Server thread/INFO]:  Running script event 'EntityDies', event='entity dies' 
                   for script 'NO FARMS FOR YOU' 
[20:04:51] [Server thread/INFO]:  Starting InstantQueue 'NO FARMS FOR 
                   YOU_IncentiveRangeHybrid'... 
[20:04:51] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_IncentiveRangeHybrid' Executing: 
                   FLAG "server" 
                   "spawnlimit.<context.entity.location.simple>:++" 
                   "duration:30m" 
[20:04:51] [Server thread/INFO]: +- Executing dCommand: FLAG ---------+ 
[20:04:51] [Server thread/INFO]:  Filled tag <context.entity.location.simple> with 
                   '-1636,10,2456,prosperus'. 
[20:04:51] [Server thread/INFO]: +> Executing 'FLAG': 
                   flag_name='SPAWNLIMIT.-1636,10,2456,PROSPERUS'  
                   Action/Value='INCREASE(1)'  duration='d@1800.0s'  
                   flag_target='server' 
[20:04:51] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_IncentiveRangeHybrid' Executing: 
                   IF 
                   "<server.flag[spawnlimit.<context.entity.location.simple>]>" 
                   ">=" "3" "{" "-" "determine" "NO_DROPS_OR_XP" "-" 
                   "narrate" "Debug message" "}" 
[20:04:51] [Server thread/INFO]: +- Executing dCommand: IF ---------+ 
[20:04:51] [Server thread/INFO]: +> Executing 'IF': use_braces='true' 
[20:04:51] [pool-1486080-thread-1/INFO]:  Filled tag <context.entity.location.simple> with 
                   '-1636,10,2456,prosperus'. 
[20:04:51] [Server thread/INFO]:  Filled tag 
                   <server.flag[spawnlimit.-1636,10,2456,prosperus]> with 
                   '1.0'. 
[20:04:51] [Server thread/INFO]:  Comparable='Decimal(1.0)', Operator='OR_MORE', 
                   ComparedTo='Decimal(3.0)' --> OUTCOME='false' 
[20:04:51] [Server thread/INFO]:  Completing queue 'NO FARMS FOR YOU_IncentiveRangeHybrid' 
                   in 1ms. 
[20:04:56] [Server thread/INFO]:  Running script event 'EntityDies', event='entity dies' 
                   for script 'NO FARMS FOR YOU' 
[20:04:56] [Server thread/INFO]:  Starting InstantQueue 'NO FARMS FOR 
                   YOU_ActivitiesCatchAnticipated'... 
[20:04:56] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_ActivitiesCatchAnticipated' 
                   Executing: FLAG "server" 
                   "spawnlimit.<context.entity.location.simple>:++" 
                   "duration:30m" 
[20:04:56] [Server thread/INFO]: +- Executing dCommand: FLAG ---------+ 
[20:04:56] [Server thread/INFO]:  Filled tag <context.entity.location.simple> with 
                   '-1659,64,2369,prosperus'. 
[20:04:56] [Server thread/INFO]: +> Executing 'FLAG': 
                   flag_name='SPAWNLIMIT.-1659,64,2369,PROSPERUS'  
                   Action/Value='INCREASE(1)'  duration='d@1800.0s'  
                   flag_target='server' 
[20:04:56] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_ActivitiesCatchAnticipated' 
                   Executing: IF 
                   "<server.flag[spawnlimit.<context.entity.location.simple>]>" 
                   ">=" "3" "{" "-" "determine" "NO_DROPS_OR_XP" "-" 
                   "narrate" "Debug message" "}" 
[20:04:56] [Server thread/INFO]: +- Executing dCommand: IF ---------+ 
[20:04:56] [Server thread/INFO]: +> Executing 'IF': use_braces='true' 
[20:04:56] [pool-1486083-thread-1/INFO]:  Filled tag <context.entity.location.simple> with 
                   '-1659,64,2369,prosperus'. 
[20:04:56] [Server thread/INFO]:  Filled tag 
                   <server.flag[spawnlimit.-1659,64,2369,prosperus]> with 
                   '1.0'. 
[20:04:56] [Server thread/INFO]:  Comparable='Decimal(1.0)', Operator='OR_MORE', 
                   ComparedTo='Decimal(3.0)' --> OUTCOME='false' 
[20:04:56] [Server thread/INFO]:  Completing queue 'NO FARMS FOR 
                   YOU_ActivitiesCatchAnticipated' in 1ms. 
[20:04:56] [Server thread/INFO]:  Running script event 'MythicMobsDeathEvent', event='mm 
                   denizen death' for script 'NO FARMS FOR YOU' 
[20:04:56] [Server thread/INFO]:  Starting InstantQueue 'NO FARMS FOR 
                   YOU_MovementsTargetBattery'... 
[20:04:56] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_MovementsTargetBattery' 
                   Executing: FLAG "server" 
                   "spawnlimit.<context.activemob.location.simple>:++" 
                   "duration:30m" 
[20:04:56] [Server thread/INFO]: +- Executing dCommand: FLAG ---------+ 
[20:04:56] [Server thread/INFO]:  Filled tag <context.activemob.location.simple> with 
                   '-1659,64,2369,prosperus'. 
[20:04:56] [Server thread/INFO]: +> Executing 'FLAG': 
                   flag_name='SPAWNLIMIT.-1659,64,2369,PROSPERUS'  
                   Action/Value='INCREASE(1)'  duration='d@1800.0s'  
                   flag_target='server' 
[20:04:56] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_MovementsTargetBattery' 
                   Executing: IF 
                   "<server.flag[spawnlimit.<context.activemob.location.simple>]>" 
                   ">=" "3" "{" "-" "determine" "drops:li@;money:0;exp:0" "-" 
                   "narrate" "Debug message" "}" 
[20:04:56] [Server thread/INFO]: +- Executing dCommand: IF ---------+ 
[20:04:56] [Server thread/INFO]: +> Executing 'IF': use_braces='true' 
[20:04:56] [pool-1486086-thread-1/INFO]:  Filled tag <context.activemob.location.simple> with 
                   '-1659,64,2369,prosperus'. 
[20:04:56] [Server thread/INFO]:  Filled tag 
                   <server.flag[spawnlimit.-1659,64,2369,prosperus]> with 
                   '2.0'. 
[20:04:56] [Server thread/INFO]:  Comparable='Decimal(2.0)', Operator='OR_MORE', 
                   ComparedTo='Decimal(3.0)' --> OUTCOME='false' 
[20:04:56] [Server thread/INFO]:  Completing queue 'NO FARMS FOR 
                   YOU_MovementsTargetBattery' in 1ms. 
```

**Comment by BerndiVader** [comment] 2017-06-06 19:24
Hello! I think your problem is elsewhere. The if is false on entity dies
and on mm death event:

[20:04:56] [Server thread/INFO]:  Comparable='Decimal(2.0)',
Operator='OR_MORE',
                   ComparedTo='Decimal(3.0)' --> OUTCOME='false'

[20:04:56] [Server thread/INFO]:  Comparable='Decimal(1.0)',
Operator='OR_MORE',
                   ComparedTo='Decimal(3.0)' --> OUTCOME='false'


2017-06-06 21:06 GMT+02:00 SXRWahrheit <notifications@github.com>:

**Comment by SXRWahrheit** [comment] 2017-06-06 19:27
Yes, that's because it's only supposed to cancel after the third mob.

Actually, it looks like I pulled the logs from the wrong part of the world. One moment.

**Comment by SXRWahrheit** [comment] 2017-06-06 19:30
Here's a good example:

```
[20:28:20] [Server thread/INFO]:  Running script event 'MythicMobsDeathEvent', event='mm 
                   denizen death' for script 'NO FARMS FOR YOU' 
[20:28:20] [Server thread/INFO]:  Starting InstantQueue 'NO FARMS FOR 
                   YOU_ChanDischargeCargo'... 
[20:28:20] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_ChanDischargeCargo' Executing: 
                   FLAG "server" 
                   "spawnlimit.<context.activemob.location.simple>:++" 
                   "duration:30m" 
[20:28:20] [Server thread/INFO]: +- Executing dCommand: FLAG ---------+ 
[20:28:20] [Server thread/INFO]:  Filled tag <context.activemob.location.simple> with 
                   '-7383,22,-5912,prosperus'. 
[20:28:20] [Server thread/INFO]: +> Executing 'FLAG': 
                   flag_name='SPAWNLIMIT.-7383,22,-5912,PROSPERUS'  
                   Action/Value='INCREASE(1)'  duration='d@1800.0s'  
                   flag_target='server' 
[20:28:20] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_ChanDischargeCargo' Executing: IF 
                   "<server.flag[spawnlimit.<context.activemob.location.simple>]>" 
                   ">=" "3" "{" "-" "determine" "drops:li@;money:0;exp:0" "-" 
                   "narrate" "Debug message" "}" 
[20:28:20] [Server thread/INFO]: +- Executing dCommand: IF ---------+ 
[20:28:20] [Server thread/INFO]: +> Executing 'IF': use_braces='true' 
[20:28:20] [pool-1486973-thread-1/INFO]:  Filled tag <context.activemob.location.simple> with 
                   '-7383,22,-5912,prosperus'. 
[20:28:20] [Server thread/INFO]:  Filled tag 
                   <server.flag[spawnlimit.-7383,22,-5912,prosperus]> with 
                   '260.0'. 
[20:28:20] [Server thread/INFO]:  Comparable='Decimal(260.0)', Operator='OR_MORE', 
                   ComparedTo='Decimal(3.0)' --> OUTCOME='true' 
[20:28:20] [Server thread/INFO]:  Queue 'NO FARMS FOR YOU_ChanDischargeCargo' Executing: 
                   DETERMINE "drops:li@;money:0;exp:0" 
[20:28:20] [Server thread/INFO]: +- Executing dCommand: DETERMINE ---------+ 
[20:28:20] [Server thread/INFO]: +> Executing 'DETERMINE': 
                   outcome='drops:li@;money:0;exp:0'  passively='false' 
[20:28:20] [Server thread/INFO]:  Completing queue 'NO FARMS FOR YOU_ChanDischargeCargo' in 
                   0ms. 
```

**Comment by SXRWahrheit** [comment] 2017-06-06 19:30
Here you can see "260" mobs have been killed on this spot, and the determine is supposed to activate. However, I still get 3 gold for each mob kill, and items and EXP still drop.

**Comment by BerndiVader** [comment] 2017-06-06 19:41
I tried this:

```
test:
  type: world
  events:
  
        on entity dies:
          - determine NO_DROPS_OR_XP
          - narrate "Debug message"
		  
        on mm denizen death:
            - determine drops:li@;money:0;exp:0
            - narrate "Debug message"
```
And it works. The version of the addon? Is it at 0.492a?

**Comment by SXRWahrheit** [comment] 2017-06-06 19:45
I have 0.49a, I will try to get the new version.

**Comment by BerndiVader** [comment] 2017-06-06 19:57
Well, i guess this will fix the issue then. https://github.com/BerndiVader/mmDenizenAddon/blob/master/updatev0491a.txt are the changes for 491a and here are the changes for 492a: https://github.com/BerndiVader/mmDenizenAddon/blob/master/updatev0492a.txt and this is the latest version: https://github.com/BerndiVader/mmDenizenAddon/blob/master/mmDenizenAddon.jar

**Comment by SXRWahrheit** [comment] 2017-06-06 20:04
Excellent! The script appears to work now. However, I still get the "Unknown dropped 0.0 gold!" message. Is it possible to cancel the money drop entirely so the message doesn't proc?

**Comment by BerndiVader** [comment] 2017-06-06 21:00
I think i remember we talked about this once. Anyways, its not done with just simply change the displayname of the mob because MythicMobs parse the variable <mob.name> from the config not from the displayname of the entity. But you use denizen and can do this:
```
        on entity dies:
		  - if <context.entity.isactivemob> {
			- if <context.entity.activemob.displayname> == null {
			  - adjust <context.entity.activemob> stance:<context.entity.activemob.mobtype>
			} else {
			  - adjust <context.entity.activemob> stance:<context.entity.activemob.displayname>
			}
		  }

```
Add this to the _on entity dies event_ (not to the _mm death event_!) and in config.yml of mythicmobs change the <mob.name> to <mob.stance>. The stance of the mob will always be either the displayname or the mobtype.  

BTW: if the issue is solved. Please close it. This is very OT would be nice if we move on at discord or mythicmobs forum itself, its easier to search for others too.

**Comment by SXRWahrheit** [comment] 2017-06-06 21:21
The problem is that the money AMOUNT is canceled but the drop itself is not. Is there a way to cancel the drop? So it should not show a dropped gold message at all, because no gold is dropping.

I will be sure to document this on the forums so others can search it.

The "unknown" problem is a separate issue - thank you for the fix for that, I will try it. :)

**Comment by BerndiVader** [comment] 2017-06-06 21:46
Ah ok i undertand. You cant do that within the addon but you can do it in denizen by listen to the chat event and catch the message where 0.0 is dropped:

```
		on player receives message:
		  - if <context.message> contains "receive 0.0 currency for slaying" {
		    - determine CANCELLED
		  }
```
You have to replace the contains to whatever you use in the message. Its not very nice but it works.

**Closed as completed** 2018-07-01 10:40 UTC
